### ISSUE TITLE
percent character no longer supported

### ISSUE THREAD

**Issue by cscetbon** [laughingman7743/PyAthenaJDBC#18]
I get a new exception when trying to execute a query that uses the character `%`. It doesn't happen with 1.0.8 or 1.0.9 but does with 1.1.0 :

```
$ pip freeze|grep PyAthenaJDBC
PyAthenaJDBC==1.1.0

Exception when trying to execute query sql_with_percent
Traceback (most recent call last):
  File "test.py", line 97, in <module>
    raise e
ValueError: unsupported format character 'p' (0x70) at index 457
```

**Comment by laughingman7743** [comment]
If % character is included in the query, it must be escaped with %%.
The error occurs in 1.1.0 because it was necessary to change to the old Python string format with SQLAlchemy support.

**Comment by cscetbon** [comment]
oh okay ... I have to change my code then :( 
Thanks @laughingman7743
