### ISSUE TITLE
Trying to find a solution to connect to Athena from on premise local desktops/laptops with AWS credentials setup via Multi-factor Authentication.

### ISSUE THREAD

**Issue by sonalshirke** [laughingman7743/PyAthenaJDBC#20]
I'm trying to connect to Athena using pyathenajdbc.connect(). I have AWS credentials setup via Multi-factor Authentication. 

I'm making connecting using following: -

```
athena_conn = connect(access_key=AWS_KEY_ID, secret_key=AWS_SECRET, s3_staging_dir='s3://abc-pqr-xyz/processed/athena-outputs/',region_name=REGION)

athena_conn = connect(access_key=AWS_KEY_ID, secret_key=AWS_SECRET, token=AWS_SESSION_TOKEN, s3_staging_dir='s3://abc-pqr-xyz/processed/athena-outputs/',region_name=REGION)
```

In both cases I get following error:

`ERROR: _pyathenajdbc.error.DatabaseError: The security token included in the request is invalid. (Service: AmazonAthena; Status Code: 400; Error Code: UnrecognizedClientException; Request ID: 91751051-1eed-11e7-8347-153dfe3d84a6)`

I'm using boto3.Session to get AWS credentials from aws/credentials file. These credentials are setup using MFA authentication. It seems PyAthenaJDBC package does not support session_token for creating the boto session connection. Can we modify this package to implement missing feature?

### Below mentioned is my code:
```
from pyathenajdbc import connect
from pyathenajdbc.util import as_pandas
from boto3 import Session
import jpype
jvm_path = jpype.getDefaultJVMPath()

_current_credentials = Session().get_credentials()
AWS_KEY_ID = _current_credentials.access_key
AWS_SECRET = _current_credentials.secret_key
AWS_SESSION_TOKEN = _current_credentials.token
REGION = "us-east-2"

#athena_conn = connect(access_key=AWS_KEY_ID, secret_key=AWS_SECRET, s3_staging_dir='s3://abc-pqr-xyz/processed/athena-outputs/',region_name=REGION)

athena_conn = connect(access_key=AWS_KEY_ID, secret_key=AWS_SECRET, token=AWS_SESSION_TOKEN, s3_staging_dir='s3://abc-pqr-xyz/processed/athena-outputs/',region_name=REGION)

cursor = athena_conn.cursor();
query = 'SELECT * FROM xyz.ABC  limit 1;'
cursor.execute(query)
df = as_pandas(cursor)
print(df)

```

Thank you,
Sonal Shirke

**Comment by laughingman7743** [comment]
Perhaps you can access Athena without specifying ACCESS_KEY and SECRET_KEY.
https://github.com/laughingman7743/PyAthenaJDBC#instance-profile-credentials

PyAthenaJDBC retrieves the credentials from the botocore session object.
https://github.com/laughingman7743/PyAthenaJDBC/blob/master/pyathenajdbc/connection.py#L49

**Comment by sonalshirke** [comment]
@laughingman7743 any thought on why i'm getting this error? I see botocore session object also includes token. So, was just wondering what is causing this error.

Just want to clarify that I'm running the code from my local machine and not from any EC2 instance. Also, i'm not using any IAM user.

Also, I already have set of  temporary credentials via MFA. We have a internal script that sets the temporary credentials for us, these credentials are being read from the aws/credentials file in my code in local desktop.

**Comment by laughingman7743** [comment]
It may be impossible for current implementation. Since botocore is only used to acquire Credential information, it passes the acquired information to the JDBC driver, and the actual authentication processing is done by the JDBC driver.

Writing a CredentialProvider like this in Java and using ``aws_credentials_provider_class`` and ``aws_credentials_provider_arguments`` may be connected.
http://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html
```
public CustomSessionCredentialsProvider(String accessId, String secretKey, String token)
{
  //...
}
```
```
Properties myProps = new Properties();
myProps.put("aws_credentials_provider_class","com.amazonaws.athena.jdbc.CustomSessionCredentialsProvider");
String providerArgs = "My_Access_Key," + "My_Secret_Key," + "My_Token";
myProps.put("aws_credentials_provider_arguments",providerArgs);
```

**Comment by sonalshirke** [comment]
Do you have any thoughts on what what is wrong with my code? Or you think pyathenaJDBC package is not acquainted with MFA? Perhaps its a JDBC driver issue as actual authentication processing is done by the JDBC driver?

**Comment by laughingman7743** [comment]
I do not think your code is wrong. With current implementation of PyAthenaJDBC, connecting to Athena from your environment may be difficult.
Perhaps you may be able to connect in the following:
```
    conn = connect(s3_staging_dir='s3://YOUR_S3_BUCKET/path/to/',
                   region_name='us-west-2',
                   jvm_options=['-DAWS_ACCESS_KEY_ID={0}'.format('YOUR_ACCESS_KEYID'),
                                '-DAWS_SECRET_ACCESS_KEY={0}'.format('YOUR_SECRET_ACCESS_KEY'),
                                '-DAWS_SESSION_TOKEN={0}'.format('YOUR_AWS_SESSION_TOKEN')],
                   aws_credentials_provider_class='com.amazonaws.athena.jdbc.shaded.com.amazonaws.auth.EnvironmentVariableCredentialsProvider')
```

**Comment by sonalshirke** [comment]
I tried above connect and now I'm getting following error -

`pyathenajdbc.error.DatabaseError: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))`

Any thoughts? I ran export to set environment variables.

**Comment by laughingman7743** [comment]
I'd like you to set environment variables in Python code. 
```
    os.environ['AWS_ACCESS_KEY_ID'] = 'YOUR_ACCESS_KEY_ID'
    os.environ['AWS_SECRET_ACCESS_KEY'] = 'YOUR_SECRET_ACCESS_KEY'
    os.environ['AWS_SESSION_TOKEN'] = 'YOUR_AWS_SESSION_TOKEN'
    conn = connect(s3_staging_dir='s3://YOUR_S3_BUCKET/path/to/',
                   region_name='us-west-2',
                   aws_credentials_provider_class='com.amazonaws.athena.jdbc.shaded.com.amazonaws.auth.EnvironmentVariableCredentialsProvider')
```
If you can not connect with this I have no other good idea :(

**Comment by sonalshirke** [comment]
Woohoo!! It worked!!  Thank you so much!! :-)
