### ISSUE TITLE
Class not found exception - additional steps?

### ISSUE THREAD

**Issue by jraede** [laughingman7743/PyAthenaJDBC#22]
When following the documentation in the README I get:

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    region_name='us-east-1')
  File "/Library/Python/2.7/site-packages/pyathenajdbc/__init__.py", line 66, in connect
    driver_path, **kwargs)
  File "/Library/Python/2.7/site-packages/pyathenajdbc/connection.py", line 69, in __init__
    jpype.JClass(ATHENA_DRIVER_CLASS_NAME)
  File "/Library/Python/2.7/site-packages/jpype/_jclass.py", line 55, in JClass
    raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class com.amazonaws.athena.jdbc.AthenaDriver not found
```

I see that the AthenaJDBC41-1.0.1.jar file has been downloaded into the package folder, but seems like I'm missing a step here. I'm not a Java guy so is it possible there's just a shared location I need to put the jar?

Thanks

**Comment by laughingman7743** [comment]
The binary distribution of PyAthenaJDBC includes the JDBC driver.
You do not need to place the jar file in a shared location.

The error seems to be caused by a problem with Java version.
http://stackoverflow.com/questions/43006368/connecting-with-athena-using-python-and-pyathenajdbc

The Athena JDBC driver is compatible with Java 8.
http://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html#ate-jdbc-driver

Please check the version of Java.

**Comment by laughingman7743** [comment]
Currently AWS CLI/SDK supports Athena.
https://aws.amazon.com/jp/about-aws/whats-new/2017/05/amazon-athena-adds-api-cli-aws-sdk-support-and-audit-logging-with-aws-cloudtrail /

I think that it is the best way to use AWS CLI/SDK.

**Comment by gallamine** [comment]
I have a similar problem. Running Java on OSX. Installed PyAthenaJDBC via pip. The minimal pandas example and Python 3.6 results in:

```
~/anaconda/envs/python-jdbc/lib/python3.6/site-packages/pyathenajdbc/connection.py in __init__(self, s3_staging_dir, access_key, secret_key, region_name, schema_name, profile_name, credential_file, jvm_path, jvm_options, converter, formatter, driver_path, **driver_kwargs)
     67 
     68         props = self._build_driver_args(**driver_kwargs)
---> 69         jpype.JClass(ATHENA_DRIVER_CLASS_NAME)
     70         self._jdbc_conn = jpype.java.sql.DriverManager.getConnection(
     71             ATHENA_CONNECTION_STRING.format(region=self.region_name, schema=schema_name), props)

~/anaconda/envs/python-jdbc/lib/python3.6/site-packages/jpype/_jclass.py in JClass(name)
     53     jc = _jpype.findClass(name)
     54     if jc is None:
---> 55         raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
     56 
     57     return _getClassFor(jc)

java.lang.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class com.amazonaws.athena.jdbc.AthenaDriver not found
```

```
$ java -version
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)
```

**Comment by jraede** [comment]
You should use the Athena support in the latest AWS SDK release. Removes the need for the JDBC entirely.

Sent via Mobile

________________________________
