### ISSUE TITLE
Is there a way to get Athena QueryID?

### ISSUE THREAD

**Issue by doufunao** [laughingman7743/PyAthenaJDBC#24]
Hi!
Is there any way to get Athena QueryID in pyathenajdbc?
I use PyAthenaJDBC to query data and store then in local. But when I send query to Athena, it will always save the query result in s3. So I wonder if there is a way to get that directly, instead of save it to local.

Thanks,
Eva

**Comment by laughingman7743** [comment]
Hi @doufunao,

I implemented retrieve QueryID with the following pull request.
laughingman7743/PyAthenaJDBC/pull/10

So, you should be able to easily implement downloading of query results from S3.
Please check it.

**Comment by laughingman7743** [comment]
🎉 Boto3 supported Athena. 
https://boto3.readthedocs.io/en/latest/reference/services/athena.html

**Comment by tewfik-ghariani** [comment]
So what is your opinion concerning Athena's support for Boto? It is more beneficial to use the boto rather than PyAthenaJdbc? Are they equivalent ?

**Comment by doufunao** [comment]
Thank you! I will try it! Excited that Athena team to lauch API in boto3!
