### ISSUE TITLE
Desc Table Query

### ISSUE THREAD

**Issue by tewfik-ghariani** [laughingman7743/PyAthenaJDBC#26]
Hello, 
I am using PyAthenaJDBC since the beginning and I believe it has been working like a charm,
Nevertheless, I was not able to perform the query to retrieve the description of my tables, the query is ran successfully as I can check it in the history. However, whenever I use any fetch method for the cursor, i get the following error : 

> java.lang.IndexOutOfBoundsException: Index: 1, Size: 1

You may find a sample of my code below, i would appreciate any help =)

```
class PyAthenaLoader():
    def connecti(self):
        self.conn = pyathenajdbc.connect(
            s3_staging_dir="s3://bucket",
            region_name="us-east-1",
            log_path=log_path,
        )

    def desc(self, database, table):
        """
        table description

        :param database.table:
        :return:
        """
        self.connecti()
        try:
            with self.conn.cursor() as cursor:
                cursor.execute('desc {0}.{1};'.format(database, table))
                data = cursor.fetchall()
        except Exception as X:
            print(X.args[0])
            return {'success': False, 'error': X.args[0]}
        finally:
            self.conn.close()
        return {'success': True, 'data': data}
```

**Comment by laughingman7743** [comment]
Sorry for the late reply.

I also confirmed that this error occurred, but I have not found a way to solve it.

The reason for the error is that the meta information and the number of columns in the result set are different.
3 is returned for the getColumnCount method of the meta information. The result set should contain information for three columns col_name, data_type and comment.
However, the result set does not contain information for three columns, it only contains information for one column.

If you want to know the table definition,
I think you can do it by throwing a query `SELECT * FROM TABLE_NAME LIMIT 1` and checking its description.

**Comment by laughingman7743** [comment]
I fixed this issue with the following pull request.
laughingman7743/PyAthenaJDBC#27

Please check it.

**Comment by tewfik-ghariani** [comment]
It works perfectly! Thank youu :D =) (y)
One last thing, I would like ask you a question. I just finished a Django project using PyAthenaJDBC and at the same time, AWS released the boto SDK for athena.
My question is: Is it worth it to move from using the jdbc driver to using athena's API? Or is it wiser to keep using this module? 
I would really appreciate your opinion

**Comment by laughingman7743** [comment]
It is best to use the following library.
https://github.com/laughingman7743/PyAthena/
https://pypi.python.org/pypi/PyAthena/

**Comment by tewfik-ghariani** [comment]
oh wahoo, and doing so should I tweak my code or make significant changes?
If not, what is its advantage over boto? I'm sorry for asking so many questions but i'm trying to choose the best solution for using Athena ^^ 
Eventually, I am comfortable sticking to PyAthenaJDBC. But at the same time, I am a bit frightened that it may be more error-prone in the future

**Comment by laughingman7743** [comment]
I think that a bridge that can use Java classes in Python is a niche technology. 
PyAthenaJDBC uses JPype (https://github.com/originell/jpype/). JPype is a great library and very useful. However, I do not know whether development will continue in the future. Currently it is not actively developed and I am not familiar with JNI (Java Native Interface). Therefore it is best to use RestAPI.
