### ISSUE TITLE
Class com.amazonaws.athena.jdbc.AthenaDriver not found

### ISSUE THREAD

**Issue by shtsht** [laughingman7743/PyAthenaJDBC#3]
便利なライブラリありがとうございます。
READMEのUsageにある下記コードを実行したところ、私の環境では下記エラーが発生しました。

from pyathenajdbc import connect
conn = connect(s3_staging_dir='s3://aws-athena-query-results-hoge-us-east-1/')
try:
    with conn.cursor() as cursor:
        cursor.execute("""
        SELECT * FROM test_pyathena_jdbc.one_row
        """)
        print(cursor.description)
        print(cursor.fetchall())
finally:
    conn.close()

エラー内容は

`File "handler.py", line 121, in <module>
  conn = connect(s3_staging_dir='s3://aws-athena-query-results-hoge-us-east-1/')
File "/shared/lib/pyathenajdbc/__init__.py", line 65, in connect
  **kwargs)
File "/shared/lib/pyathenajdbc/connection.py", line 69, in __init__
  jpype.JClass(ATHENA_DRIVER_CLASS_NAME)
File "/shared/lib/jpype/_jclass.py", line 55, in JClass
  raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class com.amazonaws.athena.jdbc.AthenaDriver not found`
といったもので、AWS提供のJDBCライブラリjarのクラス読み込みでエラーが発生しています。
 jpype.JClassをjava.lang.Stringなどを引数に呼び出すとエラーは置きないのでJarの読み込みに失敗しているようです。
JPypeが原因のようなのですが調べても特に解決策が見当たらず、、、

実行環境は
　Mac上のDockerコンテナ(Amazon Linux)
　Java OpenJDK 1.7.0_121
　Python 2.7.12
なのですが、他に実行環境で満たしておくべき条件などありますでしょうか。

**Comment by laughingman7743** [comment]
Same issue:
http://stackoverflow.com/questions/43006368/connecting-with-athena-using-python-and-pyathenajdbc

I have updated README.
51b8d630364f8367d3d06f5d640a6dc19cccf0fa

Thanks,
