### ISSUE TITLE
jpype._jexception.OutOfMemoryErrorPyRaisable: java.lang.OutOfMemoryError: GC overhead limit exceeded 

### ISSUE THREAD

**Issue by arnaudsj** [laughingman7743/PyAthenaJDBC#30]
Hi,

I am running into this error after running several big queries and reusing the connection:

```
jpype._jexception.OutOfMemoryErrorPyRaisable: java.lang.OutOfMemoryError: GC overhead limit exceeded
```
Any ideas? Any way to pass the JVM args to JPype to increase the mem given to the JVM on start?

Thanks!

**Comment by laughingman7743** [comment]
The following is an example of increasing the JVM heap size.
```
from pyathenajdbc import connect

conn = connect(s3_staging_dir='s3://YOUR_BUCKET/path/to/',
               region_name='us-west-2',
               jvm_options=['-Xms1024m', '-Xmx4096m'])
try:
    with conn.cursor() as cursor:
        cursor.execute("""
        SELECT * FROM many_rows
        """)
        print(cursor.fetchall())
finally:
    conn.close()
```

When creating a connection object, you can specify JVM options with a string array.
Could you please give it a try?

**Comment by Non-PlayerCharacter** [comment]
I was also having a lot of memory use, but I was able to use multiprocessing to get around it.  My code calls athena_query(athena_connect_kwargs, sql_string), and that function uses the multiprocessing module to run execute_athena_query_in_a_subprocess() in a subprocess.

`def execute_athena_query_in_a_subprocess(athena_connect_kwargs, sql_string, ret_rows):
    import pyathenajdbc 
    
    athena_connection = pyathenajdbc.connect(**athena_connect_kwargs)
    athena_cursor = athena_connection.cursor()
    athena_cursor.execute(sql_string)
    ret_rows.extend(athena_cursor.fetchall())
    
def athena_query(athena_connect_kwargs, sql_string):
    manager = multiprocessing.Manager()
    ret_rows = manager.list()
    subprocess_running_the_query = multiprocessing.Process(target=execute_athena_query_in_a_subprocess, args=(athena_connect_kwargs, sql_string, ret_rows))
    subprocess_running_the_query.start()
    subprocess_running_the_query.join()
    ret_val = ret_rows[:]
    
    subprocess_running_the_query.terminate()
    
    del ret_rows
    del manager
    gc.collect()
    
    return ret_val
`

**Comment by arnaudsj** [comment]
Thank you @laughingman7743 - trying this now. Will update with results.

**Comment by Non-PlayerCharacter** [comment]
I also had problems with memory, so I started using the multiprocessing module.

My main code calls **athena_query(athena_connect_kwargs, sql_string)**, and that function uses multiprocessing to have a subprocess run **execute_athena_query_in_a_subprocess(athena_connect_kwargs, sql_string, ret_rows, query_finished_flag)**.

Before using this, I was running several queries that each returned 100,000 rows and my main process swelled up to 3GB.  After running this, my main process stayed at 300MB all the way through.

```
def execute_athena_query_in_a_subprocess(athena_connect_kwargs, sql_string, ret_rows, query_finished_flag):
    import pyathenajdbc 
    
    athena_connection = pyathenajdbc.connect(**athena_connect_kwargs)
    athena_cursor = athena_connection.cursor()
    print sql_string
    athena_cursor.execute(sql_string)
    all_rows = athena_cursor.fetchall()
    ret_rows.extend(all_rows)
    query_finished_flag.set()
    
def athena_query(athena_connect_kwargs, sql_string):
    query_finished_flag = multiprocessing.Event()
    manager = multiprocessing.Manager()
    ret_rows = manager.list()
    subprocess_running_the_query = multiprocessing.Process(target=execute_athena_query_in_a_subprocess, args=(athena_connect_kwargs, sql_string, ret_rows, query_finished_flag))
    subprocess_running_the_query.start()
    subprocess_running_the_query.join()
    query_finished_flag.wait()
    ret_val = ret_rows[:]
    
    subprocess_running_the_query.terminate()
    
    del ret_rows
    del manager
    gc.collect()
    
    return ret_val
```

**Comment by arnaudsj** [comment]
@laughingman7743, this solved my issue. I was able to go through 20M records via Athena this afternoon with those settings. Thank you so much! Would make a nice addition to the docs ;)
