### ISSUE TITLE
Cannot install with SQLAlchemy support from pypi

### ISSUE THREAD

**Issue by moosingin3space** [laughingman7743/PyAthenaJDBC#31]
When I install from pip (reproduced on macOS Sierra and Ubuntu 14.04, running both Python 2 and 3) using the command `pip install PyAthenaJDBC[SQLAlchemy]`, I get the error message `Ignoring SQLAlchemy: markers 'extra == "SQLAlchemy"' don't match your environment`.

However, when I clone the repository, then install using `pip install ./PyAthenaJDBC[SQLAlchemy]`, the installation works.

**Comment by laughingman7743** [comment]
I certainly confirmed that extra packages can not be installed from PyPI. 😱 
Anyway, please install SQLAlchemy with `pip install SQLAlchemy`. That way you can use SQLAlchmey's integration.

Python's setup.py is so hard... 😫

**Comment by laughingman7743** [comment]
```
Laughingman7743-no-MacBook-Air:~ laughingman7743$ python -V
Python 2.7.13
Laughingman7743-no-MacBook-Air:~ laughingman7743$ python -c "import setuptools;print setuptools.__version__"
36.0.1
Laughingman7743-no-MacBook-Air:~ laughingman7743$ python -c "import pip;print pip.__version__"
9.0.1
Laughingman7743-no-MacBook-Air:~ laughingman7743$ python -c "import wheel;print wheel.__version__"
0.29.0

Laughingman7743-no-MacBook-Air:~ laughingman7743$ pip install PyHive[Presto]
Collecting PyHive[Presto]
  Ignoring requests: markers 'extra == "Presto"' don't match your environment
Collecting future (from PyHive[Presto])
Installing collected packages: future, PyHive
Successfully installed PyHive-0.3.0 future-0.16.0

Laughingman7743-no-MacBook-Air:~ laughingman7743$ pip freeze
future==0.16.0
PyHive==0.3.0
```
