### ISSUE TITLE
Gets segmentation fault (core dumped) when try to execute a query

### ISSUE THREAD

**Issue by andre250** [laughingman7743/PyAthenaJDBC#33]
Hi all, in the last 3 days I've been experiencing the error **segmentation fault (core dumped)** when I try to run a query on Athena.

I've been using this lib for a long time and this started to happen when I started using the libs pymssql and pysftp in the same repo, I do not know if this can help to identify.

When debugging the error I discovered that the error happens in the _connection.py_ class in _from future.utils import iteritems_ in this line of code:
```
# Listvalues ​​and listitems definitions from Nick Coghlan's (withdrawn)
# PEP 496:
Try:
    Dict.iteritems
Except AttributeError:
    # Python 3
    Def listvalues ​​(d):
        Return list (d.values ​​())
    Def listitems (d):
        Return list (d.items ())
```

I also debug via gdb, traceback follows:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffeea6b700 (LWP 25625)]
[New Thread 0x7fffee26a700 (LWP 25626)]
[New Thread 0x7fffe9a69700 (LWP 25627)]
2017-06-29 22: 21: 23.198238 - Downloading sms ...
Installing openjdk unwinder
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so-gdb.py", line 52, in <module >
    Class Types (object):
  File "/usr/share/gdb/auto-load/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so-gdb.py", line 66, in Types
    Nmethodp_t = gdb.lookup_type ('nmethod'). Pointer ()
Gdb.error: No type named nmethod.

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fffcfc552b4 in ?? ()
```

After bt full command

```
# 0 0x00007fffcfc552b4 in ?? ()
No symbol table info available.
# 1 0x0000000000000246 in ?? ()
No symbol table info available.
# 2 0x00007fffcfc55160 in ?? ()
No symbol table info available.
# 3 0x00007fffffff8da0 in ?? ()
No symbol table info available.
# 4 0x00007fffffff8d40 in ?? ()
No symbol table info available.
# 5 0x00007fffe0342035 in VM_Version :: get_processor_features () () from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

Can anyone help me with this problem?

**Comment by laughingman7743** [comment]
Currently boto3 supports Athena.
http://boto3.readthedocs.io/en/latest/reference/services/athena.html

I think that it is the best way to use boto3.
If you want to use the Python DB API interface, you should use PyAthena(https://github.com/laughingman7743/PyAthena) on the boto3 base.

**Comment by apurvis** [comment]
@laughingman7743 is there any reason to use the JDBC approach to Athena any more? any advantages or you just think boto3 is better all around?

**Comment by laughingman7743** [comment]
@apurvis 
In the past Athena only supported JDBC connection. So I wrote this library to use from Airflow and Redash. It seems that JDBC uses RestAPI inside AWS, so there seems to be no advantage to use JDBC in Python.
I plan to maintain for the time being. But If you want to use DB-API, I think it is better to use PyAthena.
