### ISSUE TITLE
Possible to get S3 filename?

### ISSUE THREAD

**Issue by travisbrady** [laughingman7743/PyAthenaJDBC#40]
Currently I'm fetching a relatively large set of data using PyAthenaJDBC and the time to fetch the data tends to be extremely long. 

We've experimented with using PyAthenaJDBC to _just_ execute a query and then fetch it directly from S3 using boto and it was much faster. But this is clumsy because we don't know the query file name so fetching it must be done with mtimes and that is brittle.

Ideally we'd be able to execute a query and then just retrieve the S3 path of the query's output file. Is this possible?

thank you

**Comment by laughingman7743** [comment]
I added the output_location property to the cursor object with the following pull request.
laughingman7743/PyAthenaJDBC#36

This property was added in v1.2.0.
https://github.com/laughingman7743/PyAthenaJDBC/releases/tag/v1.2.0

You can easily implement downloading of query results from S3 as follows.
```
import os
import boto3
from pyathenajdbc import connect


conn = connect(s3_staging_dir='s3://YOUR_BUCKET/path/to/',
               region_name='us-west-2')
try:
    with conn.cursor() as cursor:
        cursor.execute("""
        SELECT * FROM one_row
        """)

        # download query results
        output_location = cursor.output_location
        print(output_location)
        boto3.client('s3').download_file(
            output_location.split('/')[2],
            '/'.join(output_location.split('/')[3:]),
            os.path.join('/tmp/', os.path.basename(output_location)))
finally:
    conn.close()
```

**Comment by travisbrady** [comment]
@laughingman7743 That's excellent. Thanks very much for the helpful response and very useful library.
