### ISSUE TITLE
Credentials file with session token using profile name does not work

### ISSUE THREAD

**Issue by djhworld** [laughingman7743/PyAthenaJDBC#51]
We use temporary credentials for accessing AWS resources, and this library doesn't seem to work when you use the `profile_name` parameter.

### Steps to reproduce

1. Get credentials (notice I have an `aws_session_token` set) 

```
$ cat ~/.aws/credentials
[my-profile]
region = eu-west-1
aws_access_key_id = ...
aws_secret_access_key = ...
aws_session_token = ...
```

2. Try to get a connection using the following code: 

```
def get_connection():
    return connect(
        profile_name="my-profile",
        s3_staging_dir='s3://bucket/foo',
        region_name=Session().region_name,
        log_path='/tmp/log.txt'
    )   
```

### Outcome

Just get the following error

```
com.amazonaws.athena.jdbc.shaded.com.amazonaws.SdkClientExceptionPyRaisable: com.amazonaws.athena.jdbc.shaded.com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain
```

I think this is because of this line

https://github.com/laughingman7743/PyAthenaJDBC/blob/master/pyathenajdbc/connection.py#L108

As the `token` is set, it sets the class name to `DefaultAWSCredentialsProvider` which is fine, but it doesn't look like it passes the profile name (`my-profile`) anywhere.

To prove this, I changed the profile name in my `~/.aws/credentials` file to just `default` (and changed `profile_name` to `default` too) and everything worked. 

Maybe a fix could be to use `ProfileCredentialsProvider` if `profile_name` is set and then pass the profile_name as a parameter?

https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/profile/ProfileCredentialsProvider.html

**Comment by laughingman7743** [comment]
If profile_name is specified, it seems to be fixed by modifying the `aws_credentials_provider_class` to use `ProfileCredentialsProvider`.
I will check on the weekend :)

**Comment by laughingman7743** [comment]
@djhworld
I tried to fix this issue. Please check the following pull requests.
laughingman7743/PyAthenaJDBC#52

Thanks,

**Comment by djhworld** [comment]
@laughingman7743 Just checked it and it works as expected, thanks for the quick turnaround!
