### ISSUE TITLE
Read an array column by pandas

### ISSUE THREAD

**Issue by hayatbellafkih** [laughingman7743/PyAthenaJDBC#63]
Hi,

Is it possible to read a column whose type is array<struct< ... >> ? I can't do this only by JDBC.

Thanks.

**Comment by laughingman7743** [comment]
The ARRAY, MAP, and STRUCT types are treated as character strings.
https://github.com/laughingman7743/PyAthenaJDBC/blob/master/tests/test_cursor.py#L235
