### ISSUE TITLE
log4j warnnings

### ISSUE THREAD

**Issue by ron819** [laughingman7743/PyAthenaJDBC#67]
I'm using version 1.3.0 and getting:

log4j:WARN No appenders could be found for logger (com.amazonaws.athena.jdbc.AthenaDriver)
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

I use the connect function (`from pyathenajdbc import connect`)
What is it ?

**Comment by laughingman7743** [comment]
The log4j configuration file was not specified. Since it made to specify the configuration file, warnings will not be output in next release 2.0.0.
