### ISSUE TITLE
New JDBC drivers

### ISSUE THREAD

**Issue by Thomas-Hirsch** [laughingman7743/PyAthenaJDBC#68]
Last week Amazon released an updated driver that brings significant performance improvements: https://docs.aws.amazon.com/athena/latest/ug/release-note-2018-08-16.html

It would be useful to update PyAthenaJDBC to include this driver so I can reap the benefits in my application (alternatively, include an interface to manually download/select the new driver - unless there already is and I've missed it).

**Comment by laughingman7743** [comment]
The JDBC driver created by Symba and the JDBC driver used by PyAthenaJDBC are incompatible.
You can specify the JAR file as below, but it seems not to work. Because the implementation inside PyAthenaJDBC uses reflection.
```
conn = connect(s3_staging_dir='s3://YOUR_S3_BUCKET/path/to/',
               region_name='us-west-2',
               driver_path='/path/to/athenajdbc.jar')
```

Do you want to use JDBC in Python? I also created a DB-API based on boto3, so how about using that?
https://github.com/laughingman7743/PyAthena

If time permits I can correspond to a new JDBC driver, but please do not expect too much.

**Comment by Thomas-Hirsch** [comment]
I'm a little confused as to the difference between PyAthena and PyAthenaJDBC, though I'm relatively new to this.

In testing my code using PyAthena, it seems performance is significantly worse (like 3-4x) than using the new Athena driver in R (it took over 2 minutes to download a 25mb file (500k rows), compared to 30 seconds in R), so anything that could improve on this would be helpful.

**Comment by laughingman7743** [comment]
It is terribly poor in performance. 😩
It seems interesting to create a new JDBC driver version in Python and compare it.

**Comment by ron819** [comment]
the new SimbaAthenaJDBC isn't free.
https://www.simba.com/blog/connecting-to-athena-using-sql-workbench/

**Comment by laughingman7743** [comment]
https://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html

> After you download the version you need, read the release notes, and review the License Agreement and Notices. 
https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC_2.0.5/docs/release-notes.txt
https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC_2.0.5/docs/LICENSE.txt
https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC_2.0.5/docs/NOTICES.txt

`License for AWS SDK for Java` 🤔

**Comment by mlovretovich** [comment]
unfortunately I think the only way to take advantage of the performance improvements is to use the StreamingResults feature which is only available in the JDBC api. I'm hoping time permits to a new JDBC driver upgrade. There seems to be more than enough reason for the extra development.
