### ISSUE TITLE
pip install PyAthenaJDBC fails jpype1 error on Windows 10

### ISSUE THREAD

**Issue by yuribudilov** [laughingman7743/PyAthenaJDBC#74]
Hello

This is just a request for help, not an issue per se.

I tried installing PyAthena on Windows 10.

First error was that VC++ compiler 14.0 was required.

This is rather odd but ok, so I installed VC++ compiler, since I have a VS 2017 license.

Now CL.exe exists, I verified it.

Then I repeated the pip installation and got a different error, log is below.

Can anyone suggest next steps?

Also, as this tool is meant to work on Linux also, so what is the C++ requirement on Linux?
Is there a doc which tells me what prerequisites I need installed for PyAthena to work on Windows and on Linux ? 

I tried running pip install from VS 2017 developer command shell, it still did not work.

I am guessing some environmental variables are not set up, but given I dont know anything about VC++, I dont know what pip needs to work. 

It would help if all non-python dependency installation steps were documented because this product is aimed for Python developers, not for C++ developers, and should cover Windows and Linux.

Thank you very much in advance.

The Log of failed installation (Windows 10, VS 2017 Professional is installed, using Python 3.7):

U:\>pip install PyAthenaJDBC
Collecting PyAthenaJDBC
  Using cached https://files.pythonhosted.org/packages/b8/45/017b913c925f812a3d7217b0783bf8e65a4cc9d2624134119d29067034e5/PyAthenaJDBC-2.0.1-py2.py3-none-any.whl
Requirement already satisfied: botocore>=1.0.0 in c:\python3\lib\site-packages (from PyAthenaJDBC) (1.12.67)
Collecting jpype1>=0.6.0 (from PyAthenaJDBC)
  Using cached https://files.pythonhosted.org/packages/c4/4b/60a3e63d51714d4d7ef1b1efdf84315d118a0a80a5b085bb52a7e2428cdc/JPype1-0.6.3.tar.gz
Requirement already satisfied: future in c:\python3\lib\site-packages (from PyAthenaJDBC) (0.17.1)
Requirement already satisfied: docutils>=0.10 in c:\python3\lib\site-packages (from botocore>=1.0.0->PyAthenaJDBC) (0.14)
Requirement already satisfied: urllib3<1.25,>=1.20; python_version >= "3.4" in c:\python3\lib\site-packages (from botocore>=1.0.0->PyAthenaJDBC) (1.24.1)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\python3\lib\site-packages (from botocore>=1.0.0->PyAthenaJDBC) (0.9.3)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1; python_version >= "2.7" in c:\python3\lib\site-packages (from botocore>=1.0.0->PyAthenaJDBC) (2.7.5)
Requirement already satisfied: six>=1.5 in c:\python3\lib\site-packages (from python-dateutil<3.0.0,>=2.1; python_version >= "2.7"->botocore>=1.0.0->PyAthenaJDBC) (1.12.0)
Installing collected packages: jpype1, PyAthenaJDBC
  Running setup.py install for jpype1 ... error
    Complete output from command c:\python3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\YURI~1.BUD\\AppData\\Local\\Temp\\pip-install-krg67r7j\\jpype1\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\YURI~1.BUD\AppData\Local\Temp\pip-record-7gn72az2\install-record.txt --single-version-externally-managed --compile:
    Found native jni.h at c:\java\java8\include
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\jpype
    copying jpype\imports.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\JClassUtil.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\nio.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\reflect.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_classpath.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_core.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_cygwin.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_darwin.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_gui.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jarray.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jboxed.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jclass.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jcollection.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jexception.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jio.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jobject.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jpackage.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jproxy.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jvmfinder.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jwrapper.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_linux.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_properties.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_pykeywords.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_refdaemon.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_windows.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\__init__.py -> build\lib.win-amd64-3.7\jpype
    creating build\lib.win-amd64-3.7\jpype\awt
    copying jpype\awt\__init__.py -> build\lib.win-amd64-3.7\jpype\awt
    creating build\lib.win-amd64-3.7\jpype\awt\event
    copying jpype\awt\event\WindowAdapter.py -> build\lib.win-amd64-3.7\jpype\awt\event
    copying jpype\awt\event\__init__.py -> build\lib.win-amd64-3.7\jpype\awt\event
    creating build\lib.win-amd64-3.7\jpypex
    copying jpypex\__init__.py -> build\lib.win-amd64-3.7\jpypex
    creating build\lib.win-amd64-3.7\jpypex\swing
    copying jpypex\swing\AbstractAction.py -> build\lib.win-amd64-3.7\jpypex\swing
    copying jpypex\swing\pyutils.py -> build\lib.win-amd64-3.7\jpypex\swing
    copying jpypex\swing\__init__.py -> build\lib.win-amd64-3.7\jpypex\swing
    running build_ext
    building '_jpype' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\native
    creating build\temp.win-amd64-3.7\Release\native\common
    creating build\temp.win-amd64-3.7\Release\native\python
    cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWIN32=1 -Inative\common\include -Inative\python\include -Ic:\java\java8\include -Ic:\java\java8\include\win32 -Ic:\python3\include -Ic:\python3\include "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\cppwinrt" /EHsc /Tpnative\common\jp_array.cpp /Fobuild\temp.win-amd64-3.7\Release\native\common\jp_array.obj /EHsc
    error: command 'cl.exe' failed: No such file or directory

    ----------------------------------------
Command "c:\python3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\YURI~1.BUD\\AppData\\Local\\Temp\\pip-install-krg67r7j\\jpype1\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\YURI~1.BUD\AppData\Local\Temp\pip-record-7gn72az2\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\YURI~1.BUD\AppData\Local\Temp\pip-install-krg67r7j\jpype1\

**Comment by laughingman7743** [comment]
JPype Installation Requirements
Windows: https://github.com/jpype-project/jpype/blob/master/doc/install.rst#windows
Linux: https://github.com/jpype-project/jpype/blob/master/doc/install.rst#debianubuntu

**Comment by laughingman7743** [comment]
I recommend using PyAthena. https://github.com/laughingman7743/PyAthena
