### ISSUE TITLE
Return the Query ID after execute query in Athena

### ISSUE THREAD

**Issue by tuanHonestbee** [laughingman7743/PyAthenaJDBC#9]
- Purpose: Get the query ID to search for the file in S3, download that file and add data to our DB.
- Current situation: We have no way to retrieve the query ID after execute the query. We need to search for the latest file in S3 and download that file.
- Proposed approach: Have a function, maybe called `getQueryID` in cursor to return the executed query ID.

**Comment by tewfik-ghariani** [comment]
Hello, 
As a matter of fact, there is a method to retrieve the query ID. It is already mentioned in the official documentation of Athena JDBC driver and it is functional within PyAthenajdbc module.

It consists in specifying the **log_path** option in the connection method

![jdbc](https://cloud.githubusercontent.com/assets/11073604/24245079/bb924260-0fc1-11e7-89cc-5d1cfe674f6b.png)
![log](https://cloud.githubusercontent.com/assets/11073604/24245090/c1629d98-0fc1-11e7-8afe-eeb6cb3f19e0.png)

> Example

```
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
athena_jdbc_driver_path = BASE_DIR + "/lib/static/AthenaJDBC.jar"
log_path = BASE_DIR + "/lib/static/queries.log"



conn = pyathenajdbc.connect(
                              s3_staging_dir="s3://athena",
                              access_key=access_key_id,
                              secret_key=secret_key_id,
                              region_name="us-east-1",
                              **log_path=log_path,**
                              driver_path=athena_jdbc_driver_path
                              )
```

**Comment by laughingman7743** [comment]
I think that it can be realized with the following simple implementation.
```
    @property
    def query_id(self):
        if not self.has_result_set:
            raise ProgrammingError('No result set.')
        return self._result_set.getClient().getQueryID()
```
I will check on the weekend.
Thanks,

**Comment by laughingman7743** [comment]
I added a property to retrieve the query_id to the cursor object with the following pull request.
laughingman7743/PyAthenaJDBC#10

Please check it.

**Comment by miltoneck** [comment]
so... that's gone?
is there a different way of doing this? 
or where did the getClient() property go?
